url: "http://janaipakos.github.io"
baseurl: ""
title: James Anaipakos
description: James Anaipakos
avatar: ""
navbar-links:
  Blog: ""
  Projects: "projec
  About Me: "about"
  Résumé: "resume"

author:
  name: James Anaipakos
  email: "janaipakos@gmail.com"
  facebook: yourname
  github: janaipakos
  twitter: yourname
  linkedin: janaipakos
  stackoverflow: yourlink
footer-links-active:
  rss: false
  facebook: false
  email: true
  twitter: false
  github: true
  linkedin: true
  stackoverflow: false
url-pretty: "janaipakos.com"
google_analytics: "56064805"
timezone: "America/Vancouver"
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
gems: [jekyll-paginate]

permalink: /:year-:month-:day-:title
paginate: 5
future: true
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: false
  -
    scope:
      path: ""
    values:
      layout: "default"

exclude:
  - CNAME
  - LICENSE
  - README.md

prose:
  rooturl: '_posts'
  media: 'img'
  ignore:
    - 404.html
    - LICENSE
    - feed.xml
    - _config.yml
    - /_layouts
    - /_includes
    - /css
    - /img
    - /js
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Post title"
          placeholder: "Title"
          alterable: true
      - name: "subtitle"
        field:
          element: "textarea"
          label: "Subtitle"
          placeholder: "A description of your post."
          alterable: true
      - name: "date"
        field:
          element: "text"
          label: "Date"
          help: "Enter date of post."
          placeholder: "yyyy-mm-dd"
          alterable: true
      - name: "published"
        field:
          element: "checkbox"
          label: "Publish"
          help: "Check to publish post, uncheck to hide."

common-css:
  - "/css/normalize.css"
  - "/css/bootstrap.min.css"
  - "/css/style.css"
  - "/css/animate-custom.css"
common-ext-css:
  - "//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css"
common-googlefonts:
  - "Source+Sans+Pro:200,300,700"
  - "Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800"
  - "Varela"
common-js:
  - "/js/jquery-1.11.2.min.js"
  - "/js/bootstrap.min.js"
  - "/js/modernizr.custom.js"
  - "/js/retina.js"
  - "/js/jquery.easing.1.3.js"
  - "/js/smoothscroll.js"
  - "/js/jquery-func.js"
common-ext-js:
  - "//code.jquery.com/jquery-migrate-1.2.1.min.js"
